#160772744 Feat/160772744/get all orders
charlesinto/sweet-spicy pull request #30
Opened 2018-09-25 21:36 UTC by charlesinto

## What does this PR do?
#### enables user to order for foood
## Description of Task to be completed?
#### Implements GET api/v1/orders endpoint
## How should this be manually tested?
#### npm run test on GET api/v1/orders
## Any background context you want to provide?
#### None
#### What are the relevant pivotal tracker stories?
#### [#160772744](https://www.pivotaltracker.com/story/show/160772744)
## Screenshots (if appropriate)
## Questions:

2018-09-26 07:56 UTC, EricDav requested changes
Please document your code

2018-09-26 07:56 UTC, EricDav commented on server/Controller/getAllOrders.js
> +        if(env === 'TEST'){
why this check?

2018-09-26 07:56 UTC, EricDav commented on server/Controller/getAllOrders.js
> +const setUpTable = () => {
no  jsdoc here

2018-09-26 07:56 UTC, EricDav commented on server/Controller/getAllOrders.js
>  export const getAllOrders = (req, res) => {
No jsdoc here

2018-09-26 07:56 UTC, EricDav commented on server/Controller/createNewOrder.js
> +
No jsdoc here

2018-09-26 21:24 UTC, charlesinto commented on server/Controller/getAllOrders.js
> +        if(env === 'TEST'){
when am running on test environment am using a different configuration, so that's what I check for

2018-09-26 21:34 UTC, charlesinto commented on server/Controller/getAllOrders.js
> +const setUpTable = () => {
Added jsdocs

2018-09-26 21:34 UTC, charlesinto commented on server/Controller/getAllOrders.js
>  export const getAllOrders = (req, res) => {
added jsdocs

2018-09-26 21:34 UTC, charlesinto commented on server/Controller/createNewOrder.js
> +
added

2018-09-27 09:34 UTC, EricDav approved these changes

2018-09-29 06:01 UTC, merged